export const allCountries = [
    { type: 'AFG', name: 'Afghanistan' },
    { type: 'ALA', name: 'Åland Islands' },
    { type: 'ALB', name: 'Albania' },
    { type: 'DZA', name: 'Algeria' },
    { type: 'ASM', name: 'American Samoa' },
    { type: 'AND', name: 'Andorra' },
    { type: 'AGO', name: 'Angola' },
    { type: 'AIA', name: 'Anguilla' },
    { type: 'ATA', name: 'Antarctica' },
    { type: 'ATG', name: 'Antigua and Barbuda' },
    { type: 'ARG', name: 'Argentina' },
    { type: 'ARM', name: 'Armenia' },
    { type: 'ABW', name: 'Aruba' },
    { type: 'AUS', name: 'Australia' },
    { type: 'AUT', name: 'Austria' },
    { type: 'AZE', name: 'Azerbaijan' },
    { type: 'BHS', name: 'Bahamas' },
    { type: 'BHR', name: 'Bahrain' },
    { type: 'BGD', name: 'Bangladesh' },
    { type: 'BRB', name: 'Barbados' },
    { type: 'BLR', name: 'Belarus' },
    { type: 'BEL', name: 'Belgium' },
    { type: 'BLZ', name: 'Belize' },
    { type: 'BEN', name: 'Benin' },
    { type: 'BMU', name: 'Bermuda' },
    { type: 'BTN', name: 'Bhutan' },
    { type: 'BOL', name: 'Bolivia, Plurinational State of' },
    { type: 'BES', name: 'Bonaire, Sint Eustatius and Saba' },
    { type: 'BIH', name: 'Bosnia and Herzegovina' },
    { type: 'BWA', name: 'Botswana' },
    { type: 'BVT', name: 'Bouvet Island' },
    { type: 'BRA', name: 'Brazil' },
    { type: 'IOT', name: 'British Indian Ocean Territory' },
    { type: 'BRN', name: 'Brunei Darussalam' },
    { type: 'BGR', name: 'Bulgaria' },
    { type: 'BFA', name: 'Burkina Faso' },
    { type: 'BDI', name: 'Burundi' },
    { type: 'KHM', name: 'Cambodia' },
    { type: 'CMR', name: 'Cameroon' },
    { type: 'CAN', name: 'Canada' },
    { type: 'CPV', name: 'Cape Verde' },
    { type: 'CYM', name: 'Cayman Islands' },
    { type: 'CAF', name: 'Central African Republic' },
    { type: 'TCD', name: 'Chad' },
    { type: 'CHL', name: 'Chile' },
    { type: 'CHN', name: 'China' },
    { type: 'CXR', name: 'Christmas Island' },
    { type: 'CCK', name: 'Cocos (Keeling) Islands' },
    { type: 'COL', name: 'Colombia' },
    { type: 'COM', name: 'Comoros' },
    { type: 'COG', name: 'Congo' },
    { type: 'COD', name: 'Congo, the Democratic Republic of the' },
    { type: 'COK', name: 'Cook Islands' },
    { type: 'CRI', name: 'Costa Rica' },
    { type: 'CIV', name: 'Côte d\'Ivoire' },
    { type: 'HRV', name: 'Croatia' },
    { type: 'CUB', name: 'Cuba' },
    { type: 'CUW', name: 'Curaçao' },
    { type: 'CYP', name: 'Cyprus' },
    { type: 'CZE', name: 'Czech Republic' },
    { type: 'DNK', name: 'Denmark' },
    { type: 'DJI', name: 'Djibouti' },
    { type: 'DMA', name: 'Dominica' },
    { type: 'DOM', name: 'Dominican Republic' },
    { type: 'ECU', name: 'Ecuador' },
    { type: 'EGY', name: 'Egypt' },
    { type: 'SLV', name: 'El Salvador' },
    { type: 'GNQ', name: 'Equatorial Guinea' },
    { type: 'ERI', name: 'Eritrea' },
    { type: 'EST', name: 'Estonia' },
    { type: 'ETH', name: 'Ethiopia' },
    { type: 'FLK', name: 'Falkland Islands (Malvinas)' },
    { type: 'FRO', name: 'Faroe Islands' },
    { type: 'FJI', name: 'Fiji' },
    { type: 'FIN', name: 'Finland' },
    { type: 'FRA', name: 'France' },
    { type: 'GUF', name: 'French Guiana' },
    { type: 'PYF', name: 'French Polynesia' },
    { type: 'ATF', name: 'French Southern Territories' },
    { type: 'GAB', name: 'Gabon' },
    { type: 'GMB', name: 'Gambia' },
    { type: 'GEO', name: 'Georgia' },
    { type: 'DEU', name: 'Germany' },
    { type: 'GHA', name: 'Ghana' },
    { type: 'GIB', name: 'Gibraltar' },
    { type: 'GRC', name: 'Greece' },
    { type: 'GRL', name: 'Greenland' },
    { type: 'GRD', name: 'Grenada' },
    { type: 'GLP', name: 'Guadeloupe' },
    { type: 'GUM', name: 'Guam' },
    { type: 'GTM', name: 'Guatemala' },
    { type: 'GGY', name: 'Guernsey' },
    { type: 'GIN', name: 'Guinea' },
    { type: 'GNB', name: 'Guinea-Bissau' },
    { type: 'GUY', name: 'Guyana' },
    { type: 'HTI', name: 'Haiti' },
    { type: 'HMD', name: 'Heard Island and McDonald Islands' },
    { type: 'VAT', name: 'Holy See (Vatican City State)' },
    { type: 'HND', name: 'Honduras' },
    { type: 'HKG', name: 'Hong Kong' },
    { type: 'HUN', name: 'Hungary' },
    { type: 'ISL', name: 'Iceland' },
    { type: 'IND', name: 'India' },
    { type: 'IDN', name: 'Indonesia' },
    { type: 'IRN', name: 'Iran, Islamic Republic of' },
    { type: 'IRQ', name: 'Iraq' },
    { type: 'IRL', name: 'Ireland' },
    { type: 'IMN', name: 'Isle of Man' },
    { type: 'ISR', name: 'Israel' },
    { type: 'ITA', name: 'Italy' },
    { type: 'JAM', name: 'Jamaica' },
    { type: 'JPN', name: 'Japan' },
    { type: 'JEY', name: 'Jersey' },
    { type: 'JOR', name: 'Jordan' },
    { type: 'KAZ', name: 'Kazakhstan' },
    { type: 'KEN', name: 'Kenya' },
    { type: 'KIR', name: 'Kiribati' },
    { type: 'PRK', name: 'Korea, Democratic People\'s Republic of' },
    { type: 'KOR', name: 'Korea, Republic of' },
    { type: 'KWT', name: 'Kuwait' },
    { type: 'KGZ', name: 'Kyrgyzstan' },
    { type: 'LAO', name: 'Lao People\'s Democratic Republic' },
    { type: 'LVA', name: 'Latvia' },
    { type: 'LBN', name: 'Lebanon' },
    { type: 'LSO', name: 'Lesotho' },
    { type: 'LBR', name: 'Liberia' },
    { type: 'LBY', name: 'Libya' },
    { type: 'LIE', name: 'Liechtenstein' },
    { type: 'LTU', name: 'Lithuania' },
    { type: 'LUX', name: 'Luxembourg' },
    { type: 'MAC', name: 'Macao' },
    { type: 'MKD', name: 'Macedonia, the former Yugoslav Republic of' },
    { type: 'MDG', name: 'Madagascar' },
    { type: 'MWI', name: 'Malawi' },
    { type: 'MYS', name: 'Malaysia' },
    { type: 'MDV', name: 'Maldives' },
    { type: 'MLI', name: 'Mali' },
    { type: 'MLT', name: 'Malta' },
    { type: 'MHL', name: 'Marshall Islands' },
    { type: 'MTQ', name: 'Martinique' },
    { type: 'MRT', name: 'Mauritania' },
    { type: 'MUS', name: 'Mauritius' },
    { type: 'MYT', name: 'Mayotte' },
    { type: 'MEX', name: 'Mexico' },
    { type: 'FSM', name: 'Micronesia, Federated States of' },
    { type: 'MDA', name: 'Moldova, Republic of' },
    { type: 'MCO', name: 'Monaco' },
    { type: 'MNG', name: 'Mongolia' },
    { type: 'MNE', name: 'Montenegro' },
    { type: 'MSR', name: 'Montserrat' },
    { type: 'MAR', name: 'Morocco' },
    { type: 'MOZ', name: 'Mozambique' },
    { type: 'MMR', name: 'Myanmar' },
    { type: 'NAM', name: 'Namibia' },
    { type: 'NRU', name: 'Nauru' },
    { type: 'NPL', name: 'Nepal' },
    { type: 'NLD', name: 'Netherlands' },
    { type: 'NCL', name: 'New Caledonia' },
    { type: 'NZL', name: 'New Zealand' },
    { type: 'NIC', name: 'Nicaragua' },
    { type: 'NER', name: 'Niger' },
    { type: 'NGA', name: 'Nigeria' },
    { type: 'NIU', name: 'Niue' },
    { type: 'NFK', name: 'Norfolk Island' },
    { type: 'MNP', name: 'Northern Mariana Islands' },
    { type: 'NOR', name: 'Norway' },
    { type: 'OMN', name: 'Oman' },
    { type: 'PAK', name: 'Pakistan' },
    { type: 'PLW', name: 'Palau' },
    { type: 'PSE', name: 'Palestinian Territory, Occupied' },
    { type: 'PAN', name: 'Panama' },
    { type: 'PNG', name: 'Papua New Guinea' },
    { type: 'PRY', name: 'Paraguay' },
    { type: 'PER', name: 'Peru' },
    { type: 'PHL', name: 'Philippines' },
    { type: 'PCN', name: 'Pitcairn' },
    { type: 'POL', name: 'Poland' },
    { type: 'PRT', name: 'Portugal' },
    { type: 'PRI', name: 'Puerto Rico' },
    { type: 'QAT', name: 'Qatar' },
    { type: 'REU', name: 'Réunion' },
    { type: 'ROU', name: 'Romania' },
    { type: 'RUS', name: 'Russian Federation' },
    { type: 'RWA', name: 'Rwanda' },
    { type: 'BLM', name: 'Saint Barthélemy' },
    { type: 'SHN', name: 'Saint Helena, Ascension and Tristan da Cunha' },
    { type: 'KNA', name: 'Saint Kitts and Nevis' },
    { type: 'LCA', name: 'Saint Lucia' },
    { type: 'MAF', name: 'Saint Martin (French part)' },
    { type: 'SPM', name: 'Saint Pierre and Miquelon' },
    { type: 'VCT', name: 'Saint Vincent and the Grenadines' },
    { type: 'WSM', name: 'Samoa' },
    { type: 'SMR', name: 'San Marino' },
    { type: 'STP', name: 'Sao Tome and Principe' },
    { type: 'SAU', name: 'Saudi Arabia' },
    { type: 'SEN', name: 'Senegal' },
    { type: 'SRB', name: 'Serbia' },
    { type: 'SYC', name: 'Seychelles' },
    { type: 'SLE', name: 'Sierra Leone' },
    { type: 'SGP', name: 'Singapore' },
    { type: 'SXM', name: 'Sint Maarten (Dutch part)' },
    { type: 'SVK', name: 'Slovakia' },
    { type: 'SVN', name: 'Slovenia' },
    { type: 'SLB', name: 'Solomon Islands' },
    { type: 'SOM', name: 'Somalia' },
    { type: 'ZAF', name: 'South Africa' },
    { type: 'SGS', name: 'South Georgia and the South Sandwich Islands' },
    { type: 'SSD', name: 'South Sudan' },
    { type: 'ESP', name: 'Spain' },
    { type: 'LKA', name: 'Sri Lanka' },
    { type: 'SDN', name: 'Sudan' },
    { type: 'SUR', name: 'Suriname' },
    { type: 'SJM', name: 'Svalbard and Jan Mayen' },
    { type: 'SWZ', name: 'Swaziland' },
    { type: 'SWE', name: 'Sweden' },
    { type: 'CHE', name: 'Switzerland' },
    { type: 'SYR', name: 'Syrian Arab Republic' },
    { type: 'TWN', name: 'Taiwan, Province of China' },
    { type: 'TJK', name: 'Tajikistan' },
    { type: 'TZA', name: 'Tanzania, United Republic of' },
    { type: 'THA', name: 'Thailand' },
    { type: 'TLS', name: 'Timor-Leste' },
    { type: 'TGO', name: 'Togo' },
    { type: 'TKL', name: 'Tokelau' },
    { type: 'TON', name: 'Tonga' },
    { type: 'TTO', name: 'Trinidad and Tobago' },
    { type: 'TUN', name: 'Tunisia' },
    { type: 'TUR', name: 'Turkey' },
    { type: 'TKM', name: 'Turkmenistan' },
    { type: 'TCA', name: 'Turks and Caicos Islands' },
    { type: 'TUV', name: 'Tuvalu' },
    { type: 'UGA', name: 'Uganda' },
    { type: 'UKR', name: 'Ukraine' },
    { type: 'ARE', name: 'United Arab Emirates' },
    { type: 'GBR', name: 'United Kingdom' },
    { type: 'USA', name: 'United States' },
    { type: 'UMI', name: 'United States Minor Outlying Islands' },
    { type: 'URY', name: 'Uruguay' },
    { type: 'UZB', name: 'Uzbekistan' },
    { type: 'VUT', name: 'Vanuatu' },
    { type: 'VEN', name: 'Venezuela, Bolivarian Republic of' },
    { type: 'VNM', name: 'Vietnam' },
    { type: 'VGB', name: 'Virgin Islands, British' },
    { type: 'VIR', name: 'Virgin Islands, U.S.' },
    { type: 'WLF', name: 'Wallis and Futuna' },
    { type: 'ESH', name: 'Western Sahara' },
    { type: 'YEM', name: 'Yemen' },
    { type: 'ZMB', name: 'Zambia' },
    { type: 'ZWE', name: 'Zimbabwe' }
];
